# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1adf3a7c83945f64516ab26b7b695616"
name = "shop-demo"
handle = "shop-demo-17"
application_url = "https://aa-latina-universities-an.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "favorpan.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://aa-latina-universities-an.trycloudflare.com/auth/callback",
  "https://aa-latina-universities-an.trycloudflare.com/auth/shopify/callback",
  "https://aa-latina-universities-an.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
